export default {
    ADD_SOFTWARE: 'ADD_SOFTWARE',
    DELETE_SOFTWARE: 'DELETE_SOFTWARE',
    UPLOAD_SOFTWARE: 'UPLOAD_SOFTWARE',
    GET_SOFTWARES: 'GET_SOFTWARES',
    GET_SOFTWARE: 'GET_SOFTWARE'
}